ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = system;

CREATE USER hotel IDENTIFIED BY Admin123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CONNECT TO hotel;
GRANT RESOURCE TO hotel;
GRANT DBA TO hotel;

GRANT EXECUTE ON DBMS_LOCK TO hotel;
